language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: KRU1LaTicnsp82N+wpe8J/aW3+tX+DGc3q2I65O+uGiGXK17UTp0o/4lKwLp2QFi9Zge4TMSYBhTpPFLf9Gx6fNUoXJp5D4ig3vXbmgiMqzzgSQWHNh2pPeFCQI65WKVNKSng0hn/KToPRXsz2lhv79EYdU1Rhr3KNwKqdGGPtr3My6Gp6jbDfldCrGAkfWDQF9ZyXvAJ1fah0axAn5AdRHRAuG9o0wUKpD2rXiIODS6+qoaL3jvS02rALrxn3Z+USH4SMua67ckL3r35SUEjm56QBt7/o/q0b2FCbprbIl9uEKv5FAWrvDhnhxKCZuVmBm7hjO0B4RFt2Mfn25908RKTHEIXiOVjdbIjd91McX4XYg0smZoxFpPWnVM9qyRIQa2kZwJRxbte/bqH0t2YkD/UM3X6rlsqOiVL5YvfxXG9MuZmQg6w7KjcqEiC8T46Yrm9/Sa9JkHUIwGNlJVqPKAqq6vA70RnFIMZL99xP+6YKA7burQY3FHSBvbTejsa0sGYBl+1Lbd1Lswt/VPDUZ4JMDw3JYh+/7VU8SqF7JBEylyZKC+i5S2vqPCpSQWn4mBfNDiGfNzyGgrY0dYERYrXxSihm+90nxFcbDbCCTq8/SCBJLMfGFWjoxwDjHtBhRCYwyENPtZutHKmiB6upti+XdaOhNmAiXUdgwj8zk=
  app: guarded-thicket-83395
  on:
    repo: jmkeller3/wait2plate-client
    branch: testing_forms
